backend:
  name: github
  repo: Baokhang070803/am-coffee-and-cake  # Tên repository GitHub của bạn
  branch: main  # Hoặc nhánh bạn đang sử dụng
  client_id: lv23liiAlfpFNzovZ3S3a  # Client ID từ GitHub
  client_secret: 55d307a11ec84c8b6d17b19a1c31dc5ace5cf2f7  # Client Secret mới

media_folder: "images"  # Thư mục chứa hình ảnh tải lên
public_folder: "/images"  # Đường dẫn công khai cho hình ảnh


collections:
  - name: "products"
    label: "Sản Phẩm"
    folder: "images/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tên Sản Phẩm", name: "title", widget: "string" }
      - { label: "Mô Tả", name: "description", widget: "text" }
      - { label: "Giá", name: "price", widget: "number" }
      - { label: "Hình Ảnh", name: "image", widget: "image" }

backend:
  client_id: lv23liiAlfpFNzovZ3S3a  # Client ID từ GitHub
  client_secret: 9e94fefa128f5c2dd5b0081a1569440fb27999be  # Client Secret từ GitHub

admin:
  url: "https://amcoffeeandcake.netlify.app/admin"
